# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:  
      - ./data-mysql:/var/lib/mysql
      - ./cosmetic.sql:/cosmetic.sql
networks:
    default:
        external:
            name: cosmetic_network      
