version: '3.1'

services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment: 
         - PMA_HOST=db
    ports:
         - '8081:80'   
networks:
    default:
        external:
            name: cosmetic_network   
